[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["npm install --legacy-peer-deps", "DATABASE_URL='postgresql://dummy:dummy@localhost/dummy' npx prisma generate", "npm run build"]

[start]
cmd = "npm start"
